### PR TITLE
Update md eda

### PR DESCRIPTION
**Pull request by ntuziyihuang**
I update the directory of my HDD.md and I also redo the EDA report. 
For the eda part, I stopped at the merged data, since I think we need more discussion and improve our EDA progressively. There seems to be some meaningful column in SCADA data that can probably help us identify the occurrences of the false.

And in the HDD.md file, it contains the goal of our project and the preliminary objective function and constraints that can be used for the model optimization .

Additionally, I also create a new environment instead of updating it directly for easier tracking of the expansion of the environment in the process stage.

### CODE REVIEW

**Comment by JavierACM** [comment]
@ntuziyihuang Did you forget to add reviewers?

**Comment by ajhaller** [comment]
@ntuziyihuang Quick note: the branch name does not use the appropriate branch naming conventions

**Comment by ntuziyihuang** [comment]
> @ntuziyihuang Did you forget to add reviewers?

Yes, I forgot to do so. Now I add @ajhaller and @rr-85 as my reviewers

**Comment by ntuziyihuang** [comment]
> @ntuziyihuang Quick note: the branch name does not use the appropriate branch naming conventions
Got it, I will follow the naming conventions later on

**Review by ajhaller — COMMENTED** [review]
Looks good.

**Pull request closed without merging**
